FROM python:3.10-slim

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"

RUN pip install --no-cache-dir -U pip setuptools wheel

WORKDIR /app

COPY requirements.txt .

RUN pip install -r /app/requirements.txt

COPY src/initial-organization .
COPY src/lib .

RUN mkdir -p /data/assets
RUN mkdir -p /data/base-data

ENTRYPOINT ["python", "/app/organize.py"]
